name: arrugas_domain
description: Dominio de la applicación de arrugas

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.10.1
  flame_audio: ^2.1.3

  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 1.0.0

flutter:
  generate: true
  uses-material-design: true
