flutter_launcher_icons:
  android: true # can specify file name here e.g. "ic_launcher"
  # 710x599
  image_path_android: "assets/launcher_icon/ic_launcher.png"

  # only available for Android 8.0 devices and above
  # The color (E.g. "#ffffff") or image asset (E.g. "christmas-background.png") which will be used to fill out the background of the adaptive icon.
  # adaptive_icon_background: "#5f0aff"
  adaptive_icon_background: "assets/launcher_icon/ic_launcher_adaptive_back.png"

  # only available for Android 8.0 devices and above
  #  The image asset which will be used for the icon foreground of the adaptive icon Note: Adaptive Icons will only be generated when both adaptive_icon_background and adaptive_icon_foreground are specified. (the image_path is not automatically taken as foreground)
  adaptive_icon_foreground: "assets/launcher_icon/ic_launcher_adaptive_fore.png"

  min_sdk_android: 21 # android min sdk min:16, default 21

  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # 1024x1024
  image_path_ios: "assets/launcher_icon/icon.png"
  remove_alpha_ios: true
