name: arrugas
description: Arrugas videogame

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.10.1
  flame_audio: ^2.1.3

  rxdart: ^0.27.7

  arrugas_domain:
    git:
      url: git@github.com/unirtfe/unirtfe.github.io.git
      path: src/domain
      ref: main
  arrugas_layout:
    git:
      url: git@github.com/unirtfe/unirtfe.github.io.git
      path: src/layout
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: 5.3.1
  build_runner: any
  coolint: 1.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/hubs/
    - assets/audio/music/
    - assets/images/episodes/episode1/
    - assets/images/episodes/episode2/
    - assets/images/episodes/episode3/
    - assets/images/episodes/episode4/
    - assets/images/episodes/episode5/
    - assets/images/episodes/episode6/
    - assets/images/episodes/episode7/
    - assets/images/episodes/episode8/
    - assets/images/episodes/episode9/
    - assets/images/episodes/episode10/
    - assets/images/episodes/episode11/
    - assets/images/episodes/episode12/
    - assets/images/episodes/episode13/
    - assets/images/episodes/episode14/
    - assets/images/games/episode2/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/colors/colors.xml
  fonts:
    enabled: true
  # Optional
  integrations:
    # flutter_svg: true
    # flare_flutter: false
    # rive: true
    lottie: false
